### ISSUE TITLE
Icons change randomly on purchase

### ISSUE THREAD

**Issue by TrebyC** [fsphys/nanposweb#1] opened 2023-04-03 16:31 UTC

**Comment by AlexanderKaschta** [comment] 2023-04-03 22:00
This is the intended behavior of the code, see https://github.com/fsphys/nanposweb/blob/main/nanposweb/templates/index.html#L65-L70 for reference. As there is a general lack in documentation and therefore this isn't written down. This might not be a great UX but required more user feedback.

Please be a litte bit more specific when reporting. Currently there's no contributing guide, but a description detailing you issues with code/software and what behavior you would expect is helpful.

This issue will be closed as this is not a bug and this is a mirror of the original repository. The main development team will focus on the issue tracker of the original repository as it's the main development platform.

**Closed as not planned by AlexanderKaschta** 2023-04-03 22:00 UTC
